from __future__ import annotations

import argparse
import json
from pathlib import Path

from evaluation.paired import evaluate_promotion_records, load_paired_records, load_rating_profiles


def main() -> int:
    project = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description="Evaluate a paired Candidate vs Champion gate")
    parser.add_argument("--input", type=Path, required=True, help="Paired JSONL generated by an evaluator")
    parser.add_argument("--profile", required=True, help="Rating profile name")
    parser.add_argument(
        "--presets",
        type=Path,
        default=project / "config" / "rating_presets.toml",
    )
    parser.add_argument("--resamples", type=int, default=5000)
    parser.add_argument("--confidence", type=float, default=0.95)
    parser.add_argument("--min-rating-mean", type=float, default=0.0)
    parser.add_argument("--min-rating-lower", type=float, default=0.0)
    parser.add_argument("--min-rank-improvement", type=float, default=0.0)
    parser.add_argument("--max-last-place-regression", type=float, default=0.003)
    parser.add_argument("--bootstrap-seed", type=int, default=0)
    parser.add_argument("--json-out", type=Path)
    args = parser.parse_args()

    rows = load_paired_records(args.input)
    profiles = load_rating_profiles(args.presets)
    if args.profile not in profiles:
        raise SystemExit(f"Unknown rating profile: {args.profile}")

    decision = evaluate_promotion_records(
        rows,
        profile_name=args.profile,
        profile=profiles[args.profile],
        resamples=args.resamples,
        confidence=args.confidence,
        min_rating_mean=args.min_rating_mean,
        min_rating_lower=args.min_rating_lower,
        min_rank_improvement=args.min_rank_improvement,
        max_last_place_regression=args.max_last_place_regression,
        bootstrap_seed=args.bootstrap_seed,
    )
    payload = {
        "passed": decision.passed,
        "reason": decision.reason,
        "profile": args.profile,
        "games": len(rows),
        "players": rows[0].players,
        "seed_clusters": len({row.seed for row in rows}),
        "bootstrap_unit": "seed-cluster",
        "metrics": [
            {
                "name": metric.name,
                "passed": metric.passed,
                "required": metric.required,
                "min_mean": metric.min_mean,
                "min_lower": metric.min_lower,
                "n": metric.estimate.n,
                "clusters": metric.estimate.clusters,
                "mean_delta": metric.estimate.mean_delta,
                "lower": metric.estimate.lower,
                "upper": metric.estimate.upper,
                "confidence": metric.estimate.confidence,
            }
            for metric in decision.metrics
        ],
    }
    text = json.dumps(payload, ensure_ascii=False, indent=2)
    print(text)
    if args.json_out:
        args.json_out.parent.mkdir(parents=True, exist_ok=True)
        args.json_out.write_text(text + "\n", encoding="utf-8")
    return 0 if decision.passed else 10


if __name__ == "__main__":
    raise SystemExit(main())
